REGIONS = {'PHA': 'Hlavní město Praha',
           'STC': 'Středočeský',
           'JHC': 'Jihočeský',
           'PLK': 'Plzeňský',
           'KVK': 'Karlovarský',
           'ULK': 'Ústecký',
           'LBK': 'Liberecký',
           'HKK': 'Královéhradecký',
           'PAK': 'Pardubický',
           'OLK': 'Olomoucký',
           'MSK': 'Moravskoslezský',
           'JHM': 'Jihomoravský',
           'ZLK': 'Zlínský',
           'VYS': 'Kraj Vysočina',
           }
NUMS_REGIONS = {0: 'PHA',
                1: 'STC',
                2: 'JHC',
                3: 'PLK',
                4: 'KVK',
                5: 'ULK',
                6: 'LBK',
                7: 'HKK',
                14: 'PAK',
                15: 'OLK',
                16: 'MSK',
                17: 'JHM',
                18: 'ZLK',
                19: 'VYS',
                }
REGIONS_NUMS = {'PHA': 0,
                'STC': 1,
                'JHC': 2,
                'PLK': 3,
                'KVK': 4,
                'ULK': 5,
                'LBK': 6,
                'HKK': 7,
                'PAK': 14,
                'OLK': 15,
                'MSK': 16,
                'JHM': 17,
                'ZLK': 18,
                'VYS': 19
                }
DATA_WEB_ROOT = "data/"
DATA_FILES = {2016: "datagis2016.zip",
              2017: "datagis-rok-2017.zip",
              2018: "datagis-rok-2018.zip",
              2019: "datagis-rok-2019.zip",
              2020: "datagis-09-2020.zip"
              }
DATA_HEADER = ['p1', 'p36', 'p37', 'p2a', 'weekday(p2a)', 'p2b', 'p6', 'p7', 'p8', 'p9', 'p10',
               'p11', 'p12', 'p13a', 'p13b', 'p13c', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19',
               'p20', 'p21', 'p22', 'p23', 'p24', 'p27', 'p28', 'p34', 'p35', 'p39', 'p44',
               'p45a', 'p47', 'p48a', 'p49', 'p50a', 'p50b', 'p51', 'p52', 'p53', 'p55a', 'p57',
               'p58', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'n', 'o', 'p', 'q',
               'r', 's', 't', 'p5a', 'reg'
               ]
