REGIONS = {'PHA': 'Hlavní město Praha',
           'STC': 'Středočeský',
           'JHC': 'Jihočeský',
           'PLK': 'Plzeňský',
           'KVK': 'Karlovarský',
           'ULK': 'Ústecký',
           'LBK': 'Liberecký',
           'HKK': 'Královéhradecký',
           'PAK': 'Pardubický',
           'OLK': 'Olomoucký',
           'MSK': 'Moravskoslezský',
           'JHM': 'Jihomoravský',
           'ZLK': 'Zlínský',
           'VYS': 'Kraj Vysočina',
           }
REGIONS2 = {0: 'PHA',
            1: 'STC',
            2: 'JHC',
            3: 'PLK',
            4: 'KVK',
            5: 'ULK',
            6: 'LBK',
            7: 'HKK',
            14: 'PAK',
            15: 'OLK',
            16: 'MSK',
            17: 'JHM',
            18: 'ZLK',
            19: 'VYS',
            }
